### ISSUE TITLE
Add pre-shared key per peer

### ISSUE THREAD

**Issue by jnk0** [voxpupuli/puppet-wireguard#46]
Wireguard can use an optional pre-shared key per peer [1], in order to increase safety. This has not yet been implemented in this module. Can you add this parameter?

[1] https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8

**Comment by jhammons** [comment]
Indeed. This seems to be a necessary configuration parameter now. Without it, I was unable to receive a handshake between peers.
